# Analysis title
analysis: p22074_Peijian_Analysis
# short name to identify reference genome version, used to label outputs
reference: GRCm38
# Reference genome directory
referenceDir: mus_musculus/GRCm38/ensembl_102/GRCm38_102_S2.7.9a 
# STAR feature counts files directory
alignmentDir: /yerkes-cifs/runs/Analysis/2022_Analyses/p22074_Peijian/p22074_Peijian_Processing/S2.7.9a_GRCm38
# Suffix used to identify read count tables output by STAR
STARreadSuffix: _ReadsPerGene.out.tab
# Samples to drop, using the same names as the "sample ID" column of the exp_design_template
dropSamples:
-
design: Group + Batch
# Level of primary design factor to use as baseline for comparisons in heatmap
designBaseline: Cont
groupPairs: # Use group factors from exp_design_template
- FAC_vs_Cont
- LiproxposFAC_vs_Cont
- MTposFAC_vs_Cont
geneList:
- PWP1
pcaMapping: #should be column names in the exp_design file
  color: Group
  shape: Batch
  label: Individual
alpha: 0.05 #adjusted P value cutoff
# Order that samples appear on figures. List order of metadata factors (columns in exp_design_template) to sort by
sampleGrouping: 
- Group
- Batch
