## {{i}}

```{r}
summary(DESeq_results${{i}})
```

```{r}
print(DESeq_results${{i}}@elementMetadata$description[2])
```
  
```{r}
generateVolcanoPlot(DESeq_results${{i}}, labels = tlr_genes)
```

```{r}
generateDGEDatatable(DESeq_results${{i}})
```

```{r, fig.height=8}
heatmapFromGenelist(geneList = getTopNGenes(DESeq_results${{i}}),
                    baseline_grouping = 'Group',
                    baseline = 'Cont',
                    data = assays(analysis$dds)$rld[,sort(rownames(colData(analysis$dds)))],
                    column_split = c(rep(1,3), rep(2,3), rep(3,3), rep(4,3)),
                    slice_labels = c('Cont', 'Fac', 'Group3', 'Group4'),
                    slice_labels_rot = 45)
```

***

```{text, eval = FALSE}
## call the script with knitr::knit_expand in a formatfile to dynamically render chunks
out <- NULL
for (celltype in celltypes) {
    out = c(out, knitr::knit_expand(text = chunk_text, celltype = celltype))
}

cat(knit_child(text = out, quiet = TRUE), sep = '\n')
```
