---
title: "model_validation"
author: "ENPRC Gencore"
date:  "`r Sys.Date()`"
output: 
  rmdformats::robobook:
    fig_width: 9
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE, 
                      echo=FALSE,
                      fig.width = 6,
                      fig.height = 4,
                      dev='png')
library(tidyverse)    ## General logic and processing
# library(DESeq2)       ## Makes us have a job
library(here)         ## For consistent directory structures
library(edgeR)
library(DT)
library(reshape2)
```

# Read metadata

```{r}
obj <- readRDS('/yerkes-cifs/runs/analyst/micah/Analysis/2023_Analyses/p23224_Matthew//p23224_Matthew_Analysis/rds/report-01/bulk-p23224_Matthew-no_design_yet.rds')
metadata <- as.data.frame(obj$md$sampleTable)
exp_data <- obj$dge
plots <- list()
```

```{r}
metadata %>%
  select(-c(FileID, SampleID, grp.day, readPath))
  # select(sampleID, SubjectID, grp)
```

```{r}
relevant_cols <- colnames(metadata %>% select(-c(FileID, SampleID, grp.day, readPath, sampleID)))
metadata_summary <- lapply(relevant_cols, function(x) table(unlist((metadata[[x]]))))
names(metadata_summary) <- relevant_cols
metadata_summary
```

```{r}
table(metadata$SubjectID, metadata$grp)
```

```{r}
table(metadata$SubjectID, metadata$day)
```

```{r}
table(metadata$response, metadata$grp)
```

```{r}
table(metadata$response, metadata$SubjectID)
```

# Set levels

```{r}
metadata$day <- factor(metadata$day, levels = c('P14', 'D00', 'D03', 'D07', 'D28'))
metadata$grp <- factor(metadata$grp, levels = c('grp2', 'grp3'))
```


# Design

```{r}
design_formula <- as.formula('~ day + grp + grp:day')
design_matrix  <- stats::model.matrix(design_formula, data = metadata)
colnames(design_matrix)
```

## Fit design

```{r}
model_fit <- edgeR::voomLmFit(counts = obj$dge,
                              design = design_matrix,
                              block = metadata$SubjectID,
                              sample.weights = TRUE)
```

# Define contrasts

Explicitly write out full contrast formulas, including terms that will cancel.
This avoids mistakes and facilitates plotting.

Remember to use valid names, which may differ from the original names

```{r}
make.names(colnames(design_matrix))
```


```{r}
contrast_matrix_expanded <- data.frame(
  contrast_names = c(
    'P14_grp3vgrp2',
    'D00_grp3vgrp2',
    'D03_grp3vgrp2',
    'D07_grp3vgrp2',
    'D28_grp3vgrp2'
  ),
  numerators = c(
    'X.Intercept. + grpgrp3',
    'X.Intercept. + grpgrp3 + dayD00 + dayD00.grpgrp3',
    'X.Intercept. + grpgrp3 + dayD03 + dayD03.grpgrp3',
    'X.Intercept. + grpgrp3 + dayD07 + dayD07.grpgrp3',
    'X.Intercept. + grpgrp3 + dayD28 + dayD28.grpgrp3'
  ),
  denominators = c(
    'X.Intercept.',
    'X.Intercept. + dayD00',
    'X.Intercept. + dayD03',
    'X.Intercept. + dayD07',
    'X.Intercept. + dayD28'
  )
)
```

```{r}
contrast_matrix <- apply(contrast_matrix_expanded, MARGIN = 1, function(row) {
  paste0('(', row[2], ') - (', row[3], ')')
})
contrast_matrix <- limma::makeContrasts(contrasts = contrast_matrix,
    levels = make.names(colnames(design_matrix)))
colnames(contrast_matrix) <- contrast_matrix_expanded$contrast_names
contrast_matrix
```

## Extract contrasts

```{r}
## Re-orient the fitted model object from the coefficients of the original design matrix to the set of contrasts defined above in contr.matrix
extracted_contrasts <- contrasts.fit(model_fit, contrasts = contrast_matrix)
  ## Run empirical Bayes moderation; borrowing information across all the genes to obtain more precise estimates of gene-wise variability
extracted_contrasts <- eBayes(extracted_contrasts, robust=TRUE)
  ## Plot the model's residual variances against average expression values; demonstrating that the variance is no longer dependent on the mean expression level
plotSA(extracted_contrasts, main="Final model: Mean-variance trend")
  ## Identify which genes are significantly differentially expressed for each contrast from a fit object containing p-values and test statistics
extracted_contrasts$sig <- decideTests(extracted_contrasts, lfc = 0)
```

```{r}
createResTables <- function(obj) {
  resultsTables <- list()
  for (contrast in colnames(obj$contrasts)) {
    resultsTables[[contrast]] <- topTable(obj, coef = contrast, n = Inf) %>%
      # as_tibble(rownames = "gene") %>%
      dplyr::rename(log2FoldChange = logFC, pvalue = P.Value, padj = adj.P.Val)
  }
  return(resultsTables)
}

# Arrange by cluster, then by contrast
resTables <- createResTables(extracted_contrasts)

# Put all the results in a single table
resTable_AllOneTbl <- lapply(resTables, function(one_tbl) {
    one_tbl %>%
    rownames_to_column(var = "gene")
  }) %>% bind_rows(., .id = "contrast")
```

```{r}
resTable_AllOneTbl
```

```{r}
# checkplot <- function(gene,
#                       model_fit, 
#                       extracted_contrasts,
#                       contrast_matrix_expanded,
#                       metadata,
#                         metadata_id_col = 'sampleID',
#                         metadata_x_col = 'day',
#                         metadata_group_col = 'grp'
#                       ) 
base_expression <- model_fit$EList$E[gene,] %>%
  stack() 
base_expression <- merge(base_expression, metadata,
                         by.x = 'ind', by.y = metadata_id_col)

coefs <- limma_fit$fit$coefficients[gene_to_plot,]
names(coefs) <- make.names(names(coefs))
contrast_mat <- extracted_contrasts$contrasts

coef_lines <- contrast_matrix_expanded
coef_lines$numerators <- lapply(coef_lines$numerators, function(x) {
  x <- x %>% 
    strsplit(split = '\\s+') %>%
    unlist()
  x[x %in% rownames(contrast_mat)] <- coefs[x[x %in% rownames(contrast_mat)]]
  x <- eval(parse(text=paste(x, collapse = ' ')))
})

coef_lines$denominators <- lapply(coef_lines$denominators, function(x) {
  x <- x %>% 
    strsplit(split = '\\s+') %>%
    unlist()
  x[x %in% rownames(contrast_mat)] <- coefs[x[x %in% rownames(contrast_mat)]]
  x <- eval(parse(text=paste(x, collapse = ' ')))
})

coef_lines <- list(
  'P14_grp2' = unname(coef_lines['(Intercept)']),
  'P14_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['grpgrp3']),
  'D00_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD00']),
  'D00_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD00'] + coef_lines['grpgrp3']+ coef_lines['dayD00:grpgrp3']),
  'D03_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD03']),
  'D03_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD03'] + coef_lines['grpgrp3']+ coef_lines['dayD03:grpgrp3']),
  'D07_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD07']),
  'D07_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD07'] + coef_lines['grpgrp3']+ coef_lines['dayD07:grpgrp3']),
  'D28_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD28']),
  'D28_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD28'] + coef_lines['grpgrp3']+ coef_lines['dayD28:grpgrp3'])
)
coef_lines <- stack(coef_lines) %>%
  separate(ind, into = c('timepoint', 'group'), sep = '_') %>%
  mutate(timepoint = factor(timepoint, levels = c('P14', 'D00', 'D03', 'D07', 'D28')),
         group = factor(group, levels = c('grp2', 'grp3')),
         group_timepoint = paste0(group, '_', timepoint))

deg_lines <- resTable_AllOneTbl %>%
  filter(gene == gene_to_plot) %>%
  select(contrast, log2FoldChange, padj) %>%
  # separate(contrast, into = c('timepoint', 'group'), sep = '_') %>%
  mutate(
    timepoint = sub(x = contrast, '(^D[0-9]+).+', '\\1'),
    timepoint = factor(timepoint, levels = c('P14', 'D00', 'D03', 'D07', 'D28')))
deg_lines <- data.frame(
  contrast = deg_lines$contrast,
  x = deg_lines$timepoint,
  ystart = coef_lines[coef_lines$group == 'grp2' & coef_lines$timepoint !='P14', 'values'],
  yend   = coef_lines[coef_lines$group == 'grp2' & coef_lines$timepoint !='P14', 'values'] + deg_lines$log2FoldChange,
  alpha = 1 - deg_lines$padj
)
# %>% mutate(
#   x = sub(pattern = '(^.[0-9]+).+', replacement =  '\\1', x = x)
# )

plots[['JUN']] <- ggplot(data = base_expression, aes(x = timepoint, y = values, group = group_timepoint, color = group, shape = SampleID)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE, position = position_dodge(width=1), width = .25) +
  geom_point(size = 2, position = position_jitterdodge(dodge.width = 1)) +
  scale_shape_manual(values = 1:12) + 
  theme_minimal() +
  labs(x = 'Timepoint', y = 'Log-fold expression', color = 'Group', alpha = '1 - adj.pval', title = gene_to_plot) +
  geom_point(data=coef_lines, shape=95, size=10) +
  geom_segment(data = deg_lines, aes(x = x, xend = x, y = ystart, yend = yend, alpha = alpha), arrow = arrow(), inherit.aes = FALSE) +
  theme(panel.grid.major.x = element_blank()) +
  guides(alpha = NULL)
plots['JUN']
```

```{r}
gene_to_plot <- c('DACT1')
base_expression <- limma_fit$fit$EList$E[gene_to_plot,] %>%
  stack() %>% 
  # rownames_to_column('SampleID') %>%
  separate(ind, into = c('SampleID', 'group', 'timepoint'), sep = '_') %>%
  mutate(timepoint = factor(timepoint, levels = c('P14', 'D00', 'D03', 'D07', 'D28')),
         group = factor(group, levels = c('grp2', 'grp3')),
         group_timepoint = paste0(group, '_', timepoint))

coef_lines <- limma_fit$fit$coefficients[gene_to_plot,]
coef_lines <- list(
  'P14_grp2' = unname(coef_lines['(Intercept)']),
  'P14_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['grpgrp3']),
  'D00_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD00']),
  'D00_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD00'] + coef_lines['grpgrp3']+ coef_lines['dayD00:grpgrp3']),
  'D03_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD03']),
  'D03_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD03'] + coef_lines['grpgrp3']+ coef_lines['dayD03:grpgrp3']),
  'D07_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD07']),
  'D07_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD07'] + coef_lines['grpgrp3']+ coef_lines['dayD07:grpgrp3']),
  'D28_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD28']),
  'D28_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD28'] + coef_lines['grpgrp3']+ coef_lines['dayD28:grpgrp3'])
)
coef_lines <- stack(coef_lines) %>%
  separate(ind, into = c('timepoint', 'group'), sep = '_') %>%
  mutate(timepoint = factor(timepoint, levels = c('P14', 'D00', 'D03', 'D07', 'D28')),
         group = factor(group, levels = c('grp2', 'grp3')),
         group_timepoint = paste0(group, '_', timepoint))

deg_lines <- resTable_AllOneTbl %>%
  filter(gene == gene_to_plot) %>%
  select(contrast, log2FoldChange, padj) %>%
  # separate(contrast, into = c('timepoint', 'group'), sep = '_') %>%
  mutate(
    timepoint = sub(x = contrast, '(^D[0-9]+).+', '\\1'),
    timepoint = factor(timepoint, levels = c('P14', 'D00', 'D03', 'D07', 'D28')))
deg_lines <- data.frame(
  contrast = deg_lines$contrast,
  x = deg_lines$timepoint,
  ystart = coef_lines[coef_lines$group == 'grp2' & coef_lines$timepoint !='P14', 'values'],
  yend   = coef_lines[coef_lines$group == 'grp2' & coef_lines$timepoint !='P14', 'values'] + deg_lines$log2FoldChange,
  alpha = 1 - deg_lines$padj
)
# %>% mutate(
#   x = sub(pattern = '(^.[0-9]+).+', replacement =  '\\1', x = x)
# )

plots[['DACT1']] <- ggplot(data = base_expression, aes(x = timepoint, y = values, group = group_timepoint, color = group, shape = SampleID)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE, position = position_dodge(width=1), width = .25) +
  geom_point(size = 2, position = position_jitterdodge(dodge.width = 1)) +
  scale_shape_manual(values = 1:12) + 
  theme_minimal() +
  labs(x = 'Timepoint', y = 'Log-fold expression', color = 'Group', alpha = '1 - adj.pval', title = gene_to_plot) +
  geom_point(data=coef_lines, shape=95, size=10) +
  geom_segment(data = deg_lines, aes(x = x, xend = x, y = ystart, yend = yend, alpha = alpha), arrow = arrow(), inherit.aes = FALSE) +
  theme(panel.grid.major.x = element_blank()) +
  guides(alpha = NULL)
plots['DACT1']
```

## Different contrast

```{r}
contrast_matrix_2 <- limma::makeContrasts(
    'P14_3v2' = 'grpgrp3', ## This is only for plotting
    'D00_3v2' = 'dayD00.grpgrp3',
    'D03_3v2' = 'dayD03.grpgrp3',
    'D07_3v2' = 'dayD07.grpgrp3',
    'D28_3v2' = 'dayD28.grpgrp3',
    levels = make.names(colnames(design_matrix)))
```

# Fit model

```{r}
limma_fit$cont_fit_2 <- contrasts.fit(limma_fit$fit, contrasts = contrast_matrix_2)
limma_fit$cont_fit_2 <- eBayes(limma_fit$cont_fit_2, robust = TRUE)
limma_fit$de2 <- decideTests(limma_fit$cont_fit_2, lfc = 0)
```

```{r}
createResTables <- function(clustObj) {
  resultsTables <- list()
  for (contrast in colnames(clustObj$cont_fit_2$coefficients)) {
    resultsTables[[contrast]] <- topTable(clustObj$cont_fit_2, coef = contrast, n = Inf) %>%
      # as_tibble(rownames = "gene") %>%
      dplyr::rename(log2FoldChange = logFC, pvalue = P.Value, padj = adj.P.Val)
  }
  return(resultsTables)
}

# Arrange by cluster, then by contrast
resTables_2 <- createResTables(limma_fit)

# Put all the results in a single table
resTable_AllOneTbl_2 <- lapply(resTables_2, function(one_tbl) {
    one_tbl %>%
    rownames_to_column(var = "gene")
  }) %>% bind_rows(., .id = "contrast")
# }) 

# Can create lists in the hierarchy desired on the fly with (helpful for plotting facetted plots etc.)
resTable_AllOneTbl_2 %>% split(resTable_AllOneTbl$contrast)
```
```{r}
resTable_AllOneTbl_2
```

```{r}
gene_to_plot <- c('JUN')
base_expression <- limma_fit$fit$EList$E[gene_to_plot,] %>%
  stack() %>% 
  # rownames_to_column('SampleID') %>%
  separate(ind, into = c('SampleID', 'group', 'timepoint'), sep = '_') %>%
  mutate(timepoint = factor(timepoint, levels = c('P14', 'D00', 'D03', 'D07', 'D28')),
         group = factor(group, levels = c('grp2', 'grp3')),
         group_timepoint = paste0(group, '_', timepoint))

coef_lines <- limma_fit$fit$coefficients[gene_to_plot,]
coef_lines <- list(
  'P14_grp2' = unname(coef_lines['(Intercept)']),
  'P14_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['grpgrp3']),
  'D00_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD00']),
  'D00_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD00'] + coef_lines['grpgrp3']+ coef_lines['dayD00:grpgrp3']),
  'D03_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD03']),
  'D03_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD03'] + coef_lines['grpgrp3']+ coef_lines['dayD03:grpgrp3']),
  'D07_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD07']),
  'D07_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD07'] + coef_lines['grpgrp3']+ coef_lines['dayD07:grpgrp3']),
  'D28_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD28']),
  'D28_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD28'] + coef_lines['grpgrp3']+ coef_lines['dayD28:grpgrp3'])
)
coef_lines <- stack(coef_lines) %>%
  separate(ind, into = c('timepoint', 'group'), sep = '_') %>%
  mutate(timepoint = factor(timepoint, levels = c('P14', 'D00', 'D03', 'D07', 'D28')),
         group = factor(group, levels = c('grp2', 'grp3')),
         group_timepoint = paste0(group, '_', timepoint))

deg_lines <- resTable_AllOneTbl_2 %>%
  filter(gene == gene_to_plot) %>%
  select(contrast, log2FoldChange, padj) %>%
  # separate(contrast, into = c('timepoint', 'group'), sep = '_') %>%
  mutate(
    timepoint = sub(x = contrast, '(^.[0-9]+).+', '\\1'),
    timepoint = factor(timepoint, levels = c('P14', 'D00', 'D03', 'D07', 'D28')))
deg_lines <- data.frame(
  contrast = deg_lines$contrast,
  x = deg_lines$timepoint,
  ystart = coef_lines[coef_lines$group == 'grp2', 'values'] +
    limma_fit$fit$coefficients[gene_to_plot,'grpgrp3'] ,
  yend   = coef_lines[coef_lines$group == 'grp2', 'values'] +
    limma_fit$fit$coefficients[gene_to_plot,'grpgrp3'] + deg_lines$log2FoldChange,
  alpha = 1 - deg_lines$padj
)

# %>% mutate(
#   x = sub(pattern = '(^.[0-9]+).+', replacement =  '\\1', x = x)
# )

plots[['JUN_2']] <- ggplot(data = base_expression, aes(x = timepoint, y = values, group = group_timepoint, color = group, shape = SampleID)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE, position = position_dodge(width=1), width = .25) +
  geom_point(size = 2, position = position_jitterdodge(dodge.width = 1)) +
  scale_shape_manual(values = 1:12) + 
  theme_minimal() +
  labs(x = 'Timepoint', y = 'Log-fold expression', color = 'Group', alpha = '1 - adj.pval', title = gene_to_plot) +
  geom_point(data=coef_lines, shape=95, size=10) +
  geom_segment(data = deg_lines, aes(x = x, xend = x, y = ystart, yend = yend, alpha = alpha), arrow = arrow(), inherit.aes = FALSE) +
  theme(panel.grid.major.x = element_blank()) +
  guides(alpha = NULL)
plots[['JUN_2']]
```

```{r}
gene_to_plot <- c('DACT1')
base_expression <- limma_fit$fit$EList$E[gene_to_plot,] %>%
  stack() %>% 
  # rownames_to_column('SampleID') %>%
  separate(ind, into = c('SampleID', 'group', 'timepoint'), sep = '_') %>%
  mutate(timepoint = factor(timepoint, levels = c('P14', 'D00', 'D03', 'D07', 'D28')),
         group = factor(group, levels = c('grp2', 'grp3')),
         group_timepoint = paste0(group, '_', timepoint))

coef_lines <- limma_fit$fit$coefficients[gene_to_plot,]
coef_lines <- list(
  'P14_grp2' = unname(coef_lines['(Intercept)']),
  'P14_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['grpgrp3']),
  'D00_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD00']),
  'D00_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD00'] + coef_lines['grpgrp3']+ coef_lines['dayD00:grpgrp3']),
  'D03_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD03']),
  'D03_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD03'] + coef_lines['grpgrp3']+ coef_lines['dayD03:grpgrp3']),
  'D07_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD07']),
  'D07_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD07'] + coef_lines['grpgrp3']+ coef_lines['dayD07:grpgrp3']),
  'D28_grp2' = unname(coef_lines['(Intercept)'] + coef_lines['dayD28']),
  'D28_grp3' = unname(coef_lines['(Intercept)'] + coef_lines['dayD28'] + coef_lines['grpgrp3']+ coef_lines['dayD28:grpgrp3'])
)
coef_lines <- stack(coef_lines) %>%
  separate(ind, into = c('timepoint', 'group'), sep = '_') %>%
  mutate(timepoint = factor(timepoint, levels = c('P14', 'D00', 'D03', 'D07', 'D28')),
         group = factor(group, levels = c('grp2', 'grp3')),
         group_timepoint = paste0(group, '_', timepoint))

deg_lines <- resTable_AllOneTbl %>%
  filter(gene == gene_to_plot) %>%
  select(contrast, log2FoldChange, padj) %>%
  # separate(contrast, into = c('timepoint', 'group'), sep = '_') %>%
  mutate(
    timepoint = sub(x = contrast, '(^D[0-9]+).+', '\\1'),
    timepoint = factor(timepoint, levels = c('P14', 'D00', 'D03', 'D07', 'D28')))
deg_lines <- data.frame(
  contrast = deg_lines$contrast,
  x = deg_lines$timepoint,
  ystart = coef_lines[coef_lines$group == 'grp2' & coef_lines$timepoint !='P14', 'values'],
  yend   = coef_lines[coef_lines$group == 'grp2' & coef_lines$timepoint !='P14', 'values'] + deg_lines$log2FoldChange,
  alpha = 1 - deg_lines$padj
)
# %>% mutate(
#   x = sub(pattern = '(^.[0-9]+).+', replacement =  '\\1', x = x)
# )

plots[['DACT1']] <- ggplot(data = base_expression, aes(x = timepoint, y = values, group = group_timepoint, color = group, shape = SampleID)) +
  geom_boxplot(outlier.shape = NA, show.legend = FALSE, position = position_dodge(width=1), width = .25) +
  geom_point(size = 2, position = position_jitterdodge(dodge.width = 1)) +
  scale_shape_manual(values = 1:12) + 
  theme_minimal() +
  labs(x = 'Timepoint', y = 'Log-fold expression', color = 'Group', alpha = '1 - adj.pval', title = gene_to_plot) +
  geom_point(data=coef_lines, shape=95, size=10) +
  geom_segment(data = deg_lines, aes(x = x, xend = x, y = ystart, yend = yend, alpha = alpha), arrow = arrow(), inherit.aes = FALSE) +
  theme(panel.grid.major.x = element_blank()) +
  guides(alpha = NULL)
plots['DACT1']
```

