---
title: "model_validation"
author: "ENPRC Gencore"
date:  "`r Sys.Date()`"
output: 
  rmdformats::robobook:
    fig_width: 9
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE, 
                      echo=FALSE,
                      fig.width = 6,
                      fig.height = 4,
                      dev='png')
```

```{css}
.book .book-body .page-inner {
  max-width: 1600px;
  margin-left: auto;
  margin-right: auto;
}
```


# Review metadata {.tabset}

## All metadata

```{r}
metadata %>%
  select(-c(FileID, date, ellipse, SampleID, sizeFactor, replaceable)) %>%
  DT::datatable( 
    colnames = c('Group', 'Individual', 'Timepoint', 'Group ID'),
    rownames = TRUE,
    filter = 'top')
  # select(sampleID, SubjectID, grp)
```

## Summarize counts

```{r}
metadata_summary
```

### Samples by individual + timepoint

```{r}
table(metadata$individual, metadata$timepoint)
```

### Samples by group + timepoint

```{r}
table(metadata$Group, metadata$timepoint)
```

### Samples by individual + group

```{r}
table(metadata$individual, metadata$ind, metadata$Group)
```

# Model design

Formula:

```{r}
design_formula
```

Columns in design matrix:

```{r}
colnames(design_matrix)
```

```{r}
knitr::kable(design_matrix)
```


## Contrast matrix

```{r}
contrast_matrix_expanded %>% knitr::kable()
```


```{r}
contrast_matrix %>% t() %>% knitr::kable()
```

# Results summary

```{r}
plots[['overall_table']]
```

# Case example ISG15

Looking at ISG15 expression as an indicator of model accuracy

```{r}
plots[['ISG15_overall']]
```

```{r}
plots[["ISG15_overall_table"]]
```


```{r}
plots[['ISG15_D2']]
```


```{r}
plots[['ISG15_D14']]
```
