<!-- ## call the script with knitr::knit_expand in a formatfile to dynamically render chunks -->
<!-- out <- NULL -->
<!-- for (celltype in celltypes) { -->
<!--     out = c(out, knitr::knit_expand(text = chunk_text, celltype = celltype)) -->
<!-- } -->

<!-- cat(knit_child(text = out, quiet = TRUE), sep = '\n') -->

## {{i}}

```{r}
result <- model_results[['{{i}}']]
```


```{r}
summary(result)
```

```{r}
print(result@elementMetadata$description[2])
```
  
```{r}
generateVolcanoPlot(result) #, labels = tlr_genes
```

```{r}
generateDGEDatatable(result)
```

```{r, fig.height=8}
geneList <- getTopNGenes(result)

data_to_plot <- assays(obj)$rld
data_to_plot <- normalizeCountsForHeatmapByIndividual(
  assay(data_to_plot),
  data_to_plot@colData,
  group_var = 'Group', baseline = 'Cont', 
  individual_var = 'Individual',
  remove_baseline = TRUE)

heatmapFromGenelist(geneList = geneList, 
                    data = data_to_plot,
                    column_split = c(rep(1,3), rep(2,3), rep(3,3), rep(4,3)),
                    slice_labels = c('Cont', 'Fac', 'Group3', 'Group4'),
                    slice_labels_rot = 45)
```

***
